version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: hp_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: hp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://hp_user:1234@db:5432/hp_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - ./backend:/app
      - ./documents:/home/user/HpProject/documents
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: